### PR TITLE
Nav Bar Updated

### PR DESCRIPTION
**Pull request by Rodolfo-Reynoso**
Nav bar has been updated. 

Also the fonts issue on the Official Rules page should now have the current boldness.

### CODE REVIEW

**Comment by Rodolfo-Reynoso** [comment]
I also committed to the 'prize-claim-form' branch instead of the master.

**Comment by Rodolfo-Reynoso** [comment]
test comment

**Comment by mristic505** [comment]
So you did not commit to master branch?

**Comment by Rodolfo-Reynoso** [comment]
No, I can if you want. But I read you should commit to an external branch then merge to master when ready.

**Pull request merged**
